# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements files first to leverage Docker cache
COPY requirements-core.txt /app/
COPY web/requirements.txt /app/web/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r web/requirements.txt

# Copy the rest of the application code
COPY core /app/core
COPY price_models /app/price_models
COPY web /app/web
COPY __init__.py /app/

# Make port 8501 available to the world outside this container
EXPOSE 8501

# Run app.py when the container launches
CMD ["streamlit", "run", "web/app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
