# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements files first to leverage Docker cache
COPY requirements-core.txt /app/
COPY api/requirements.txt /app/api/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r api/requirements.txt

# Copy the rest of the application code
COPY core /app/core
COPY price_models /app/price_models
COPY api /app/api
COPY __init__.py /app/

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run app.py when the container launches
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
