# Features
YEAR_FEATURES = ['YEAR']
NUM_FEATURES = ['QUANTITY', 'TENOR OF PAYMENT', 'FREIGHT CHARGES']
CAT_FEATURES = ["EXPORTER", "EXPORTER'S COUNTRY", "IMPORTER", "COUNTRY_OF_ORIGIN", 
                "CURRENCY", "TRADE-TERM", "SHIPMENT FROM", "SHIPMENT TO"]
ALL_FEATURES = YEAR_FEATURES + NUM_FEATURES + CAT_FEATURES

# Goods Information
GOODS_INFO = {
    '52094200': 'FABRICS - WOVEN DENIM', 
    '58071000': 'ACCESSORIES - BADGE LABEL', 
    '48211000': 'ACCESSORIES - WOVEN LABEL', 
    '96071900': 'ACCESSORIES - ZIPPER', 
    '96071100': 'ACCESSORIES - ZIPPER', 
    '96061000': 'ACCESSORIES - SNAP BUTTON', 
    '59032010': 'FABRICS - POLY TEXTILE', 
    '39262090': 'ACCESSORIES - HANGER', 
    '62171000': 'ACCESSORIES - SCRAP FABRIC', 
    '60063200': 'FABRICS - SYNTHETIC',
    '60041000': 'FABRICS - KNITTED',
    '96062200': 'ACCESSORIES - METAL BUTTON'
}

# Country Options (Copied from app.py line 45)
COUNTRY_OPTIONS = ["AFGHANISTAN", "ALGERIA", "ARGENTINA", "AUSTRALIA", "AUSTRIA", "BANGLADESH", "BELARUS", "BELGIUM", "BENIN", "BHUTAN", "BOSNIA AND HERZEGOVINA", "BRAZIL", "BULGARIA", "BURKINA FASO", "CAMBODIA", "CAMEROON", "CANADA", "CHAD", "CHILE", "CHINA PEOPLE'S REPUBLIC (P.R)", "CONGO", "CROATIA", "CZECH REPUBLIC", "DENMARK", "ECUADOR", "EGYPT", "ESTONIA", "FIJI", "FINLAND", "FRANCE", "GERMANY", "GREECE", "GUYANA", "HONG KONG, SAR OF CHINA", "HUNGARY", "INDIA", "INDONESIA", "IRAQ", "IRELAND", "ITALY", "JAPAN", "KOREA, REPUBLIC OF", "KUWAIT", "KYRGYZSTAN", "LATVIA", "LEBANON", "LUXEMBOURG", "MACEDONIA", "MADAGASCAR", "MALAYSIA", "MALI", "MALTA", "MEXICO", "MOROCCO", "MYANMAR", "NAURU", "NEPAL", "NETHERLANDS", "NEW ZEALAND", "NORWAY", "OMAN", "PAKISTAN", "PAPUA NEW GUINEA", "PARAGUAY", "PERU", "PHILIPPINES", "POLAND", "PORTUGAL", "QATAR", "ROMANIA", "RUSSIAN FEDERATION", "SAN MARINO", "SAUDI ARABIA", "SERBIA", "SIERRA LEONE", "SINGAPORE", "SLOVAKIA", "SLOVENIA", "SOUTH AFRICA", "SPAIN", "SRI LANKA", "SWEDEN", "SWITZERLAND", "TAIWAN", "TAJIKISTAN", "TANZANIA", "THAILAND", "TOGO", "TUNISIA", "TURKEY", "U.S.A.", "UK", "UKRAINE", "UNITED ARAB EMIRATES (UAE)", "URUGUAY", "VANUATU", "VIETNAM", "ZIMBABWE"]

# Port Options (Copied from app.py line 59)
PORT_OPTIONS = ['EPZ', 'CHITTAGONG', 'BENAPOL', 'Burimari', 'Others', 'SHAHAJALAL INT. AIRPORT']

# Currency Options
CURRENCY_OPTIONS = ['USD', 'EUR', 'JPY', 'GBP', 'AUD', 'CAD', 'CHF', 'CNY', 'INR']

# Incoterm Options
INCOTERM_OPTIONS = ['EXW', 'FCA', 'CPT', 'CIP', 'DAP (DAF, DES, DDU)', 'DPU', 'DDP', 'FAS', 'CIF', 'FOB', 'CNF (CFR)']
